In [1]:
import tensorflow as tf
import numpy as np
import tictactoe as ttt
#from tictactoe import RL_System_PG_TF, RandomWalkEnv, ReplayBuff_PG_TF, calc_discounted_return_inplace,DNN_Random_Walk

In [3]:
N_episodes = 10
N_A = 2
N_S = 5

optimizer = tf.keras.optimizers.Adam()
random_walk_env = ttt.RandomWalkEnv()
function_approx = ttt.DNN_Random_Walk(N_A=N_A)

for _ in range(N_episodes):
    S = random_walk_env.reset()
    with tf.GradientTape() as tape:
        S_a = np.zeros((1,N_S), dtype=np.float16)
        S_a[0, S] = 1.0
        S_tf = tf.Variable(S_a)
        probs_tf = function_approx(S_tf)
        action = np.random.choice(N_A, p=probs_tf.numpy()[0])
        S_new, reward, done = random_walk_env.step(action)

        prob_tf = tf.reshape(probs_tf[:,action],(-1,1))

        performance = tf.math.log(prob_tf) * reward 
        loss_value = tf.reduce_sum(-performance, axis=-1)

    gradients = tape.gradient(loss_value, function_approx.trainable_weights)
    optimizer.apply_gradients(zip(gradients, function_approx.trainable_weights))
    print(loss_value, gradients, action)
    print(f'action: {action}')
    print()

tf.Tensor([0.], shape=(1,), dtype=float32) [<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.,  0.],
       [-0.,  0.],
       [-0.,  0.],
       [-0.,  0.],
       [-0.,  0.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.,  0.], dtype=float32)>] 0
action: 0

tf.Tensor([0.], shape=(1,), dtype=float32) [<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.,  0.],
       [-0.,  0.],
       [-0.,  0.],
       [-0.,  0.],
       [-0.,  0.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.,  0.], dtype=float32)>] 0
action: 0

tf.Tensor([0.], shape=(1,), dtype=float32) [<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0., -0.],
       [ 0., -0.],
       [ 0., -0.],
       [ 0., -0.],
       [ 0., -0.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0., -0.], dtype=float32)>] 1
action: 1

tf.Tensor([0.], shape=(1,), dtype=float32) [<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0., -

In [4]:
N_episodes = 10
N_A = 2
N_S = 5

optimizer = tf.keras.optimizers.Adam()
random_walk_env = ttt.RandomWalkEnv()
function_approx = ttt.DNN_Random_Walk(N_A=N_A)

for _ in range(N_episodes):
    S = random_walk_env.reset()
    with tf.GradientTape() as tape:
        S_a = np.zeros((1,N_S), dtype=np.float16)
        S_a[0, S] = 1.0
        S_tf = tf.Variable(S_a)
        probs_tf = function_approx(S_tf)
        action = np.random.choice(N_A, p=probs_tf.numpy()[0])
        S_new, reward, done = random_walk_env.step(action)

        prob_tf = tf.reshape(probs_tf[:,action],(-1,1))

        performance = tf.math.log(prob_tf) * reward 
        loss_value = tf.reduce_sum(-performance, axis=-1)

    gradients = tape.gradient(loss_value, function_approx.trainable_weights)
    optimizer.apply_gradients(zip(gradients, function_approx.trainable_weights))
    print(loss_value, gradients, action)
    print(f'action: {action}')
    print()

ValueError: No gradients provided for any variable: ['dnn__random__walk_1/dense_1/kernel:0', 'dnn__random__walk_1/dense_1/bias:0'].