In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tictactoe
import numpy as np

In [3]:
Qsa_dict = tictactoe.calc_Qsa_list()

40320
40320
40320
40320
40320
40320
40320
40320
40320


In [4]:
Qsa_dict

{'win': [0.6071428571428571,
  0.5357142857142857,
  0.6071428571428571,
  0.5357142857142857,
  0.6928571428571428,
  0.5357142857142857,
  0.6071428571428571,
  0.5357142857142857,
  0.6071428571428571],
 'lose': [0.2642857142857143,
  0.3357142857142857,
  0.2642857142857143,
  0.3357142857142857,
  0.19285714285714287,
  0.3357142857142857,
  0.2642857142857143,
  0.3357142857142857,
  0.2642857142857143],
 'tie': [0.12857142857142856,
  0.12857142857142856,
  0.12857142857142856,
  0.12857142857142856,
  0.11428571428571428,
  0.12857142857142856,
  0.12857142857142856,
  0.12857142857142856,
  0.12857142857142856]}

In [5]:
Qsa_a = np.array(Qsa_dict['win']) - np.array(Qsa_dict['lose'])
Qsa_a

array([0.34285714, 0.2       , 0.34285714, 0.2       , 0.5       ,
       0.2       , 0.34285714, 0.2       , 0.34285714])

In [6]:
Qsa_a.reshape(3,3)

array([[0.34285714, 0.2       , 0.34285714],
       [0.2       , 0.5       , 0.2       ],
       [0.34285714, 0.2       , 0.34285714]])

In [10]:
np.mean(Qsa_a)

0.2968253968253968

In [11]:
Qsa_b = np.array(Qsa_dict['lose']) - np.array(Qsa_dict['win'])
Qsa_b

array([-0.34285714, -0.2       , -0.34285714, -0.2       , -0.5       ,
       -0.2       , -0.34285714, -0.2       , -0.34285714])

In [12]:
np.mean(Qsa_b)

-0.2968253968253968

In [6]:
np.prod(range(2, 10))

362880

In [7]:
np.prod(range(2, 9))

40320